# Generated by Django 5.2.4 on 2026-01-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tv_device_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='room',
            name='tv_last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
