"""
Base de cartas do Perfil.

Cada carta tem uma resposta e dicas em ordem crescente de generosidade: a
primeira é quase inútil, a última quase entrega. Quanto antes você acerta,
mais vale.

`aliases` cobre as formas alternativas de escrever a resposta — a comparação
já ignora acento, caixa e artigos, então só entram aqui variações de nome.
"""

TEMAS = ["Pessoa", "Lugar", "Coisa", "Ano", "Ficção"]

CARDS = [
    # ---------------- Pessoa ----------------
    {
        "tema": "Pessoa",
        "resposta": "Albert Einstein",
        "aliases": ["einstein"],
        "dicas": [
            "Nasci na Alemanha no século XIX.",
            "Trabalhei como examinador em um escritório de patentes.",
            "Perdi a cidadania do meu país de origem e me mudei para os Estados Unidos.",
            "Ganhei o Nobel de Física, mas não pelo trabalho que me tornou famoso.",
            "Meu sobrenome virou sinônimo de gênio.",
            "Uma foto minha com a língua para fora ficou mundialmente conhecida.",
            "Escrevi que a energia é igual à massa vezes a velocidade da luz ao quadrado.",
            "Sou o autor da Teoria da Relatividade.",
        ],
    },
    {
        "tema": "Pessoa",
        "resposta": "Pelé",
        "aliases": ["edson arantes do nascimento", "pele"],
        "dicas": [
            "Nasci em Minas Gerais, mas fiz fama em São Paulo.",
            "Comecei a jogar profissionalmente ainda adolescente.",
            "Joguei quase toda a carreira em um único clube brasileiro.",
            "Estreei em Copa do Mundo aos 17 anos.",
            "Terminei a carreira jogando nos Estados Unidos.",
            "Sou o único a ser campeão do mundo três vezes como jogador.",
            "Fui eleito Atleta do Século.",
            "Me chamavam de Rei do Futebol.",
        ],
    },
    {
        "tema": "Pessoa",
        "resposta": "Frida Kahlo",
        "aliases": ["frida"],
        "dicas": [
            "Nasci na América Latina no início do século XX.",
            "Um acidente grave na juventude marcou meu corpo para sempre.",
            "Passei longos períodos de cama, e foi ali que comecei a pintar.",
            "Me casei duas vezes com o mesmo homem, também pintor.",
            "Minhas sobrancelhas marcantes viraram parte da minha imagem.",
            "Pintei dezenas de autorretratos.",
            "Minha casa azul na Cidade do México hoje é um museu.",
            "Sou a pintora mexicana mais famosa do mundo.",
        ],
    },
    {
        "tema": "Pessoa",
        "resposta": "Leonardo da Vinci",
        "aliases": ["da vinci", "leonardo"],
        "dicas": [
            "Nasci na Itália no século XV.",
            "Escrevia meus cadernos de trás para frente, em escrita espelhada.",
            "Estudei anatomia dissecando corpos.",
            "Projetei máquinas voadoras séculos antes do avião existir.",
            "Sou o exemplo clássico do homem renascentista.",
            "Desenhei um homem dentro de um círculo e um quadrado.",
            "Pintei uma ceia numa parede de convento em Milão.",
            "Pintei o quadro mais visitado do Louvre.",
        ],
    },
    {
        "tema": "Pessoa",
        "resposta": "Ayrton Senna",
        "aliases": ["senna"],
        "dicas": [
            "Nasci em São Paulo.",
            "Comecei no kart ainda criança.",
            "Corri por McLaren e Williams.",
            "Tinha fama de imbatível na chuva.",
            "Minha rivalidade com um piloto francês marcou uma era.",
            "Fui tricampeão mundial de Fórmula 1.",
            "Morri em um acidente em Ímola, em 1994.",
            "O país parou no dia do meu velório.",
        ],
    },
    {
        "tema": "Pessoa",
        "resposta": "Marie Curie",
        "aliases": ["curie", "maria sklodowska"],
        "dicas": [
            "Nasci na Polônia e me mudei para a França para estudar.",
            "Trabalhei ao lado do meu marido em um laboratório precário.",
            "Descobri dois elementos químicos novos.",
            "Um deles recebeu o nome do meu país natal.",
            "Minha filha também ganhou um Nobel.",
            "Morri por causa da exposição ao que eu mesma pesquisava.",
            "Fui a primeira mulher a ganhar um prêmio Nobel.",
            "Sou a única pessoa premiada em duas ciências diferentes.",
        ],
    },
    {
        "tema": "Pessoa",
        "resposta": "Charles Chaplin",
        "aliases": ["chaplin", "carlitos", "charlie chaplin"],
        "dicas": [
            "Nasci em Londres, em uma família muito pobre.",
            "Comecei nos palcos ainda menino.",
            "Fiz fama nos Estados Unidos e depois fui impedido de voltar para lá.",
            "Meu personagem usava bigode, bengala e sapatos enormes.",
            "Resisti ao cinema falado por anos.",
            "Dirigi um filme em que satirizo um ditador.",
            "Meu personagem era um vagabundo de bom coração.",
            "Sou o maior nome da comédia do cinema mudo.",
        ],
    },
    {
        "tema": "Pessoa",
        "resposta": "Cleópatra",
        "aliases": ["cleopatra"],
        "dicas": [
            "Vivi antes de Cristo.",
            "Governei um país africano, mas minha família tinha origem grega.",
            "Falava vários idiomas, incluindo o da população que governava.",
            "Me envolvi com dois generais romanos poderosos.",
            "Minha morte é associada a uma serpente.",
            "Fui a última faraó do meu reino.",
            "Meu país é conhecido pelas pirâmides.",
            "Sou a rainha mais famosa do Egito Antigo.",
        ],
    },
    # ---------------- Lugar ----------------
    {
        "tema": "Lugar",
        "resposta": "Paris",
        "aliases": [],
        "dicas": [
            "Sou uma cidade europeia cortada por um rio.",
            "Tenho um bairro histórico chamado Montmartre.",
            "Meu metrô é um dos mais antigos do mundo.",
            "Sou chamada de Cidade Luz.",
            "Abrigo o museu mais visitado do planeta.",
            "Uma catedral minha pegou fogo em 2019.",
            "Tenho uma torre de ferro construída para uma exposição em 1889.",
            "Sou a capital da França.",
        ],
    },
    {
        "tema": "Lugar",
        "resposta": "Amazônia",
        "aliases": ["amazonia", "floresta amazonica"],
        "dicas": [
            "Estou em mais de um país.",
            "Tenho a maior bacia hidrográfica do mundo.",
            "Abrigo povos indígenas isolados.",
            "Sou chamada de pulmão do mundo, embora o apelido seja contestado.",
            "O desmatamento é a maior ameaça contra mim.",
            "Meu principal rio deságua no Oceano Atlântico.",
            "Cubro a maior parte do norte do Brasil.",
            "Sou a maior floresta tropical do planeta.",
        ],
    },
    {
        "tema": "Lugar",
        "resposta": "Japão",
        "aliases": ["japao"],
        "dicas": [
            "Sou formado por milhares de ilhas.",
            "Tenho uma das maiores expectativas de vida do mundo.",
            "Sofro terremotos com frequência.",
            "Minha bandeira tem um círculo vermelho.",
            "Fui a única nação a sofrer ataque com bomba atômica.",
            "Exportei mangá e anime para o mundo inteiro.",
            "Tenho um monte sagrado chamado Fuji.",
            "Minha capital é Tóquio.",
        ],
    },
    {
        "tema": "Lugar",
        "resposta": "Machu Picchu",
        "aliases": ["machupicchu"],
        "dicas": [
            "Estou na América do Sul, no alto de uma montanha.",
            "Fui construído no século XV.",
            "Fiquei esquecido pelo mundo ocidental por séculos.",
            "Um explorador americano me apresentou ao mundo em 1911.",
            "Minhas pedras se encaixam sem argamassa.",
            "Sou uma das novas sete maravilhas do mundo.",
            "Fui erguido pelo povo inca.",
            "Estou no Peru.",
        ],
    },
    {
        "tema": "Lugar",
        "resposta": "Veneza",
        "aliases": [],
        "dicas": [
            "Sou uma cidade europeia à beira-mar.",
            "Fui uma república poderosa por séculos.",
            "Meus prédios estão afundando lentamente.",
            "Tenho um carnaval famoso por suas máscaras.",
            "Não tenho carros no meu centro histórico.",
            "Meus barcos negros são conduzidos de pé, com um remo só.",
            "Minhas ruas são canais.",
            "Estou na Itália.",
        ],
    },
    {
        "tema": "Lugar",
        "resposta": "Deserto do Saara",
        "aliases": ["saara", "sahara"],
        "dicas": [
            "Estou em um único continente, mas em vários países.",
            "Já fui uma região verde, milhares de anos atrás.",
            "Minha temperatura despenca à noite.",
            "Caravanas me atravessaram por séculos comerciando sal.",
            "Tenho dunas que passam de cem metros de altura.",
            "Sou maior que o Brasil inteiro.",
            "Ocupo o norte da África.",
            "Sou o maior deserto quente do mundo.",
        ],
    },
    {
        "tema": "Lugar",
        "resposta": "Rio de Janeiro",
        "aliases": ["rio"],
        "dicas": [
            "Sou uma cidade litorânea do hemisfério sul.",
            "Já fui capital do meu país.",
            "Tenho um bondinho que sobe uma montanha de pedra.",
            "Sediei uma Olimpíada.",
            "Minhas praias mais famosas se chamam Copacabana e Ipanema.",
            "Tenho um carnaval com desfile de escolas de samba.",
            "Uma estátua de braços abertos me observa do alto.",
            "Sou conhecida como Cidade Maravilhosa.",
        ],
    },
    {
        "tema": "Lugar",
        "resposta": "Egito",
        "aliases": [],
        "dicas": [
            "Estou entre dois continentes.",
            "Minha civilização antiga durou mais de três mil anos.",
            "Tenho um canal que liga dois mares e é vital para o comércio mundial.",
            "Meu rio principal é o mais longo do mundo.",
            "Meus antigos governantes eram chamados de faraós.",
            "Tenho uma estátua com corpo de leão e cabeça humana.",
            "Minhas pirâmides estão em Gizé.",
            "Minha capital é o Cairo.",
        ],
    },
    # ---------------- Coisa ----------------
    {
        "tema": "Coisa",
        "resposta": "Café",
        "aliases": ["cafe"],
        "dicas": [
            "Venho de uma planta.",
            "Fui descoberto na Etiópia, segundo a lenda.",
            "Já fui proibido em vários países.",
            "Movimentei a economia brasileira por décadas.",
            "Sou torrado e moído antes de chegar até você.",
            "Contenho cafeína.",
            "Muita gente diz que não funciona antes de me tomar.",
            "Sou servido quente, geralmente pela manhã.",
        ],
    },
    {
        "tema": "Coisa",
        "resposta": "Espelho",
        "aliases": [],
        "dicas": [
            "Existo há milhares de anos, antes feito de metal polido.",
            "Já fui considerado objeto de luxo.",
            "Quebrar-me daria sete anos de azar, segundo a superstição.",
            "Apareço em contos de fadas fazendo perguntas sobre beleza.",
            "Vampiros supostamente não aparecem em mim.",
            "Inverto a esquerda e a direita.",
            "Estou em todo banheiro.",
            "Você me olha para se ver.",
        ],
    },
    {
        "tema": "Coisa",
        "resposta": "Bicicleta",
        "aliases": [],
        "dicas": [
            "Fui inventado no século XIX.",
            "Meus primeiros modelos não tinham pedais.",
            "Tenho uma versão com roda dianteira gigante que hoje parece absurda.",
            "Sou o meio de transporte mais eficiente em energia já criado.",
            "Tenho corrente, guidão e freios.",
            "Aprender a me usar exige equilíbrio, e não se esquece mais.",
            "Tenho duas rodas e não uso combustível.",
            "Você me move pedalando.",
        ],
    },
    {
        "tema": "Coisa",
        "resposta": "Guarda-chuva",
        "aliases": ["guarda chuva", "sombrinha"],
        "dicas": [
            "Tenho mais de dois mil anos de história.",
            "Originalmente servia contra o sol, não contra a água.",
            "Já fui símbolo de status e de nobreza.",
            "Por muito tempo, homens eram ridicularizados por me usar.",
            "Vento forte me destrói com facilidade.",
            "Abrir-me dentro de casa daria azar.",
            "Tenho varetas e um cabo.",
            "Você me abre quando começa a chover.",
        ],
    },
    {
        "tema": "Coisa",
        "resposta": "Geladeira",
        "aliases": ["refrigerador"],
        "dicas": [
            "Antes de mim, usava-se gelo transportado de lugares frios.",
            "Mudei completamente a alimentação das cidades.",
            "Funciono retirando calor de dentro, e não gerando frio.",
            "Meus primeiros modelos usavam gases tóxicos.",
            "Fico ligada o tempo todo, sem descanso.",
            "As pessoas me abrem, olham e fecham sem pegar nada.",
            "Costumo ter ímãs e fotos na porta.",
            "Guardo a comida da casa.",
        ],
    },
    {
        "tema": "Coisa",
        "resposta": "Telefone celular",
        "aliases": ["celular", "smartphone", "telefone"],
        "dicas": [
            "A primeira chamada comigo foi feita em 1973.",
            "Meus primeiros modelos pesavam quase um quilo.",
            "Já fui vendido como objeto de luxo para executivos.",
            "Substituí câmera, mapa, agenda, rádio e lanterna.",
            "Hoje existem mais unidades minhas do que pessoas no mundo.",
            "Sou a primeira coisa que muita gente olha ao acordar.",
            "Tenho tela sensível ao toque e aplicativos.",
            "Você provavelmente está com um na mão agora.",
        ],
    },
    {
        "tema": "Coisa",
        "resposta": "Chocolate",
        "aliases": [],
        "dicas": [
            "Venho de uma semente.",
            "Os astecas me consumiam como bebida amarga.",
            "Já fui usado como moeda.",
            "Cheguei à Europa no século XVI.",
            "Sou tóxico para cachorros.",
            "Derreto perto da temperatura do corpo humano.",
            "Existo nas versões amargo, ao leite e branco.",
            "Sou o presente clássico da Páscoa.",
        ],
    },
    {
        "tema": "Coisa",
        "resposta": "Relógio",
        "aliases": [],
        "dicas": [
            "Minhas primeiras versões usavam sombra ou água.",
            "Fui essencial para a navegação em alto-mar.",
            "Já fui um objeto de bolso antes de ir para o pulso.",
            "As estações de trem me tornaram indispensável.",
            "Tenho versões que dependem de corda.",
            "Apareço em uma pintura famosa, derretido.",
            "Tenho ponteiros ou números que mudam sozinhos.",
            "Sirvo para marcar as horas.",
        ],
    },
    # ---------------- Ano ----------------
    {
        "tema": "Ano",
        "resposta": "1969",
        "aliases": [],
        "dicas": [
            "Estou na segunda metade do século XX.",
            "A Guerra Fria estava no auge.",
            "A internet deu seus primeiros passos com a ARPANET.",
            "Aconteceu um festival de música enorme numa fazenda em Nova York.",
            "Os Beatles fizeram seu último show ao vivo, num terraço.",
            "O Brasil vivia sob ditadura militar.",
            "Um homem pisou na Lua pela primeira vez.",
            "Neil Armstrong falou sobre um pequeno passo.",
        ],
    },
    {
        "tema": "Ano",
        "resposta": "1994",
        "aliases": [],
        "dicas": [
            "Estou na última década do século XX.",
            "O Brasil trocou de moeda.",
            "Nelson Mandela foi eleito presidente da África do Sul.",
            "Um piloto brasileiro morreu em Ímola.",
            "A Copa do Mundo foi disputada nos Estados Unidos.",
            "Um jogador italiano perdeu o pênalti decisivo.",
            "O Brasil foi tetracampeão mundial de futebol.",
            "O Plano Real entrou em vigor.",
        ],
    },
    {
        "tema": "Ano",
        "resposta": "1888",
        "aliases": [],
        "dicas": [
            "Estou no século XIX.",
            "O Brasil ainda era um império.",
            "Dom Pedro II estava fora do país, doente.",
            "Sua filha assinava os atos oficiais em seu lugar.",
            "O Brasil foi o último país das Américas a fazer o que fez neste ano.",
            "A princesa Isabel assinou uma lei em 13 de maio.",
            "A Lei Áurea foi promulgada.",
            "A escravidão foi abolida no Brasil.",
        ],
    },
    {
        "tema": "Ano",
        "resposta": "1945",
        "aliases": [],
        "dicas": [
            "Estou na metade do século XX.",
            "Um conflito de seis anos chegou ao fim.",
            "Campos de concentração foram libertados.",
            "Hitler morreu em um bunker em Berlim.",
            "A ONU foi fundada.",
            "Duas bombas atômicas foram lançadas sobre o Japão.",
            "Getúlio Vargas foi deposto no Brasil.",
            "A Segunda Guerra Mundial acabou.",
        ],
    },
    {
        "tema": "Ano",
        "resposta": "2020",
        "aliases": [],
        "dicas": [
            "Sou um ano bissexto.",
            "As Olimpíadas foram adiadas pela primeira vez em tempos de paz.",
            "Escolas e escritórios do mundo inteiro fecharam.",
            "Videochamada virou rotina de trabalho.",
            "Máscara virou item obrigatório.",
            "Uma vacina foi desenvolvida em tempo recorde.",
            "A OMS declarou uma pandemia em março.",
            "Foi o ano da chegada da covid-19.",
        ],
    },
    {
        "tema": "Ano",
        "resposta": "1500",
        "aliases": [],
        "dicas": [
            "Estou na virada de um século.",
            "A Europa vivia a era das grandes navegações.",
            "Portugal e Espanha disputavam rotas marítimas.",
            "Uma frota partiu de Lisboa rumo às Índias.",
            "Pero Vaz de Caminha escreveu uma carta ao rei.",
            "A esquadra era comandada por Pedro Álvares Cabral.",
            "Uma terra foi avistada em 22 de abril.",
            "É o ano do descobrimento do Brasil.",
        ],
    },
    {
        "tema": "Ano",
        "resposta": "2002",
        "aliases": [],
        "dicas": [
            "Estou no começo do século XXI.",
            "O euro entrou em circulação como dinheiro em espécie.",
            "Lula foi eleito presidente do Brasil pela primeira vez.",
            "Uma Copa do Mundo foi disputada em dois países asiáticos.",
            "A final foi contra a Alemanha.",
            "Ronaldo marcou os dois gols da final.",
            "O Brasil venceu por 2 a 0 em Yokohama.",
            "O Brasil se tornou pentacampeão mundial.",
        ],
    },
    {
        "tema": "Ano",
        "resposta": "1889",
        "aliases": [],
        "dicas": [
            "Estou no fim do século XIX.",
            "A Torre Eiffel foi inaugurada em Paris.",
            "O Brasil vinha de uma abolição recente.",
            "Militares estavam insatisfeitos com o governo.",
            "A família imperial partiu para o exílio.",
            "Deodoro da Fonseca liderou o movimento.",
            "Aconteceu em 15 de novembro.",
            "É o ano da Proclamação da República no Brasil.",
        ],
    },
    # ---------------- Ficção ----------------
    {
        "tema": "Ficção",
        "resposta": "Harry Potter",
        "aliases": ["harry"],
        "dicas": [
            "Fui criado por uma autora britânica.",
            "Perdi meus pais quando era bebê.",
            "Fui criado por tios que me detestavam.",
            "Dormia embaixo de uma escada.",
            "Tenho uma cicatriz na testa em forma de raio.",
            "Estudei em uma escola chamada Hogwarts.",
            "Jogo quadribol montado numa vassoura.",
            "Sou o bruxo mais famoso da literatura.",
        ],
    },
    {
        "tema": "Ficção",
        "resposta": "Batman",
        "aliases": ["bruce wayne", "homem morcego"],
        "dicas": [
            "Apareci pela primeira vez em 1939.",
            "Vi meus pais serem assassinados quando criança.",
            "Sou bilionário, mas escondo isso do meu trabalho noturno.",
            "Não tenho superpoderes.",
            "Meu maior inimigo usa maquiagem de palhaço.",
            "Tenho um mordomo chamado Alfred.",
            "Protejo uma cidade chamada Gotham.",
            "Meu símbolo é projetado no céu com um holofote.",
        ],
    },
    {
        "tema": "Ficção",
        "resposta": "Chapeuzinho Vermelho",
        "aliases": ["chapeuzinho"],
        "dicas": [
            "Sou de um conto europeu com séculos de idade.",
            "Minha versão original é bem mais sombria que a atual.",
            "Recebi um pedido da minha mãe antes de sair.",
            "Atravesso uma floresta sozinha.",
            "Levo uma cesta de comida.",
            "Vou visitar minha avó doente.",
            "Um lobo se disfarça na cama dela.",
            "Sou reconhecida pelo capuz vermelho.",
        ],
    },
    {
        "tema": "Ficção",
        "resposta": "Homem-Aranha",
        "aliases": ["homem aranha", "spider-man", "peter parker", "spiderman"],
        "dicas": [
            "Fui criado nos anos 1960.",
            "Era um adolescente comum e nerd.",
            "Fui picado por um animal em uma excursão escolar.",
            "Perdi meu tio por não ter agido quando podia.",
            "Aprendi que grandes poderes trazem grandes responsabilidades.",
            "Trabalhei como fotógrafo de um jornal.",
            "Me movo pela cidade balançando em teias.",
            "Meu uniforme é vermelho e azul.",
        ],
    },
    {
        "tema": "Ficção",
        "resposta": "O Senhor dos Anéis",
        "aliases": ["senhor dos aneis", "lord of the rings"],
        "dicas": [
            "Fui escrito por um professor de Oxford.",
            "Meu autor criou idiomas inteiros antes da história.",
            "Minha trama se passa em um mundo chamado Terra-média.",
            "Virei uma trilogia de filmes rodada na Nova Zelândia.",
            "Tenho anões, elfos e magos.",
            "Um grupo parte em uma jornada para destruir um objeto.",
            "Meu vilão é um olho flamejante chamado Sauron.",
            "Tudo gira em torno de um anel que precisa ser destruído.",
        ],
    },
    {
        "tema": "Ficção",
        "resposta": "Cinderela",
        "aliases": ["gata borralheira"],
        "dicas": [
            "Existem versões minhas em dezenas de culturas.",
            "Perdi minha mãe cedo.",
            "Vivo servindo à minha madrasta e suas filhas.",
            "Recebo ajuda mágica para ir a uma festa.",
            "Tenho um prazo: preciso voltar à meia-noite.",
            "Perco um calçado na escada do palácio.",
            "Um príncipe procura o pé que serve no sapatinho.",
            "Meu sapato é de cristal.",
        ],
    },
    {
        "tema": "Ficção",
        "resposta": "Star Wars",
        "aliases": ["guerra nas estrelas"],
        "dicas": [
            "Estreei nos cinemas em 1977.",
            "Fui criado por George Lucas.",
            "Minha história começa no episódio IV.",
            "Tenho uma ordem de cavaleiros que usa uma força mística.",
            "Meu vilão respira alto atrás de uma máscara preta.",
            "Tenho um robô dourado e outro que apita.",
            "Uma frase famosa minha revela um parentesco inesperado.",
            "Minhas espadas são feixes de luz.",
        ],
    },
    {
        "tema": "Ficção",
        "resposta": "Jurassic Park",
        "aliases": ["parque dos dinossauros", "jurassic"],
        "dicas": [
            "Comecei como um livro antes de virar filme.",
            "Estreei no cinema em 1993 sob direção de Steven Spielberg.",
            "Minha história se passa em uma ilha na Costa Rica.",
            "Um bilionário financia o projeto.",
            "O DNA foi extraído de insetos presos em âmbar.",
            "Um matemático avisa que aquilo vai dar errado.",
            "Um copo d'água tremendo anuncia a chegada de algo enorme.",
            "Sou o filme que trouxe dinossauros de volta à vida.",
        ],
    },
]
